//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IM3DEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_IM3DEditorTYPE              129
#define IDR_TOOLBAR_FORM_VIEW           130
#define IDR_TOOLBAR_SHADING_STYLE       132
#define IDR_TOOLBAR_LIGHTING            134
#define IDR_TOOLBAR_EDIT_VIEW           136
#define IDR_TOOLBAR_SIMULATION          138
#define IDB_BITMAP_SIMULATION_ICON      140
#define IDD_DIALOG_MESH_SIZE            141
#define IDR_TOOLBAR_SETUP_SIMULATION    142
#define IDD_DIALOG_SETUP_MATERIAL       144
#define IDD_DIALOG_SETUP_TOOL           145
#define IDC_EDIT_MESH_SIZE              1000
#define IDC_EDIT_SETUP_MATERIAL_SX      1001
#define IDC_EDIT_SETUP_MATERIAL_OY      1002
#define IDC_EDIT_SETUP_MATERIAL_OZ      1003
#define IDC_EDIT_SETUP_MATERIAL_OX      1004
#define IDC_SETUPTOOL_RADIO_BALL        1004
#define IDC_EDIT_SETUP_MATERIAL_SY      1005
#define IDC_SETUPTOOL_RADIO_FLAT        1005
#define IDC_EDIT6                       1006
#define IDC_EDIT_SETUP_MATERIAL_SZ      1006
#define IDC_SETUPTOOL_RADIO_FILLET      1006
#define IDC_SETUPTOOL_EDIT_DIAMETER     1007
#define IDC_SETUPTOOL_EDIT_HEIGHT       1008
#define IDC_SETUPTOOL_EDIT_CUTTING_H    1009
#define IDC_SETUPTOOL_EDIT_FILLET_R     1010
#define IDC_SETUPTOOL_STATIC_FILLET_R   1011
#define IDC_SETUP_TOOL_STATIC_CUTTINGCOLOR 1013
#define IDR_FORM_VIEW_FRONT             32773
#define IDR_FORM_VIEW_BACK              32774
#define IDR_FORM_VIEW_LEFT              32775
#define IDR_FORM_VIEW_RIGHT             32776
#define IDR_FORM_VIEW_TOP               32777
#define IDR_FORM_VIEW_BOTTOM            32778
#define IDR_FORM_VIEW_ISOMETRIC         32779
#define IDR_TOOLBAR_SHADING_STYLE_SOLID 32780
#define IDR_TOOLBAR_SHADING_STYLE_WIRE  32781
#define IDR_TOOLBAR_LIGHTING_TOP        32782
#define IDR_TOOLBAR_LIGHTING_BOTTOM     32783
#define IDR_TOOLBAR_LIGHTING_LEFT       32784
#define IDR_TOOLBAR_LIGHTING_RIGHT      32785
#define IDR_TOOLBAR_LIGHTING_FRONT      32786
#define IDR_TOOLBAR_SHADING_STYLE_SOLID_WIRE 32787
#define ID_TOOLBAR_EIDT_VIEW_CLEAR      32788
#define ID_TOOLBAR_SIMULATION_STOP      32789
#define ID_TOOLBAR_SIMULATION_START     32790
#define ID_FEM_SPLITMESH                32791
#define ID_FEM_DELAUNAYMESH             32792
#define ID_SETUP_SIMULATION_MATERIAL    32793
#define ID_SETUP_SIMULATION_TOOL        32794
#define ID_VIEW_SIMULATION              32795
#define ID_VIEW_SIMULATION_MATERIAL     32796
#define ID_VIEW_SIMULATION_TOOL         32797
#define ID_VIEW_SIMULATION_TOOLPATH     32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1014
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
